<a href="https://colab.research.google.com/github/snipverse/GenAI/blob/main/eigen_values_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

m = np.array([[1, 2],
			[2, 3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

w, v = np.linalg.eig(m)

print("Printing the Eigen values of the given square array:\n",w)
print()

print("Printing Right Eigen Vectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [2]:
import numpy as np

m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

w, v = np.linalg.eig(m)

print("Printing the Eigen values of the given square array:\n",w)
print()

print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [3]:
import tensorflow as tf

In [4]:
e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[9.178188  8.206053 ]
 [7.4271417 4.1701026]]




In [5]:
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.5833186  0.8122434]
 [ 0.8122434  0.5833186]] 

Eigen Values: 
[-1.1637533 14.512044 ]



In [6]:
e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[4.989569  9.138396  7.4754915]
 [9.324045  8.201439  7.8808227]
 [7.72885   7.4757433 3.8159533]]




In [7]:
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[ 0.7931344   0.20454572  0.5736719 ]
 [-0.2856468  -0.7069671   0.64699596]
 [-0.5379074   0.67702186  0.502292  ]] 

Eigen Values: 
[-3.6102211 -1.655364  22.272558 ]

